import importlib
import importlib.metadata
import os
import shutil
import stat
import sys
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
STORAGE_SERVICE_DIR = SCRIPT_DIR.parent
VENV_DIR = STORAGE_SERVICE_DIR / ".venv"
VENDOR_DIR = STORAGE_SERVICE_DIR / "python-vendor"
EGG_NAME = "charm_crypto_framework-0.63-py3.14-linux-x86_64.egg"
EGG_PATH = VENDOR_DIR / EGG_NAME
RUNTIME_PACKAGES = [
    ("setuptools", "setuptools"),
    ("pkg_resources", "setuptools"),
    ("_distutils_hack", "setuptools"),
    ("pip", "pip"),
    ("pyparsing", "pyparsing"),
]


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def ensure_symlink(link_path: Path, target: str) -> None:
    link_path.parent.mkdir(parents=True, exist_ok=True)
    if link_path.exists() or link_path.is_symlink():
        link_path.unlink()
    link_path.symlink_to(target)


def make_executable(path: Path) -> None:
    current = path.stat().st_mode
    path.chmod(current | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def copy_package_into_site_packages(module_name: str, site_packages: Path) -> None:
    module = importlib.import_module(module_name)
    source_path = Path(module.__file__).resolve()
    if source_path.name == "__init__.py":
        source_path = source_path.parent

    destination = site_packages / source_path.name
    if destination.exists():
        if destination.is_dir():
            shutil.rmtree(destination)
        else:
            destination.unlink()

    if source_path.is_dir():
        shutil.copytree(source_path, destination)
    else:
        shutil.copy2(source_path, destination)


def copy_distribution_metadata(distribution_name: str, site_packages: Path) -> None:
    try:
        distribution = importlib.metadata.distribution(distribution_name)
    except importlib.metadata.PackageNotFoundError:
        return

    source_dist_info = Path(distribution._path)  # noqa: SLF001
    destination = site_packages / source_dist_info.name
    if destination.exists():
        shutil.rmtree(destination)
    shutil.copytree(source_dist_info, destination)


def main() -> None:
    if not EGG_PATH.exists():
        raise FileNotFoundError(
            f"Charm runtime not found in project vendor directory: {EGG_PATH}"
        )

    python_executable = Path(sys.executable).resolve()
    version = f"{sys.version_info.major}.{sys.version_info.minor}"
    site_packages = VENV_DIR / "lib" / f"python{version}" / "site-packages"
    relative_egg = os.path.relpath(EGG_PATH, site_packages)

    write_text(
        VENV_DIR / "pyvenv.cfg",
        "\n".join([
            f"home = {python_executable.parent}",
            "include-system-site-packages = false",
            f"version = {sys.version.split()[0]}",
            "",
        ]),
    )

    ensure_symlink(VENV_DIR / "bin" / "python", str(python_executable))
    ensure_symlink(VENV_DIR / "bin" / "python3", str(python_executable))

    write_text(
        site_packages / "medchain_charm_vendor.pth",
        f"{relative_egg}\n",
    )

    for module_name, distribution_name in RUNTIME_PACKAGES:
        copy_package_into_site_packages(module_name, site_packages)
        copy_distribution_metadata(distribution_name, site_packages)

    activate_path = VENV_DIR / "bin" / "activate"
    write_text(
        activate_path,
        "\n".join([
            "# Generated by Medchain storage-service setup",
            f'export VIRTUAL_ENV="{VENV_DIR}"',
            'export PATH="$VIRTUAL_ENV/bin:$PATH"',
            "unset PYTHONHOME",
            "",
        ]),
    )
    make_executable(activate_path)

    print(f"Created project-local Python environment at: {VENV_DIR}")
    print(f"Python executable: {VENV_DIR / 'bin' / 'python'}")
    print(f"Charm vendor runtime: {EGG_PATH}")


if __name__ == "__main__":
    main()
